version: "2.1"

services:
  filebrowser:    
    build: ./hdfs-filebrowser
    image: filebrowser_image_epetxepe
    hostname: filebrowser
    container_name: filebrowser    
    networks: 
      - spark-net
    environment:
      - NAMENODE_HOST=namenode
    ports:
      - "8888:8888"    
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    env_file:
      - ./hadoop.env
    healthcheck:
      interval: 5s
      retries: 100 
    networks:
      - spark-net
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    depends_on:
      namenode:
        condition: service_healthy
    healthcheck:
      interval: 5s
      retries: 100 
    networks:
      - spark-net
  spark-master:
    image: bde2020/spark-master:3.0.1-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      namenode:
        condition: service_healthy
      datanode:
        condition: service_healthy    
    networks:
      - spark-net
  spark-worker:
    container_name: spark_worker_1
    image: bde2020/spark-worker:3.0.1-hadoop3.2
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - spark-master            
    networks:
      - spark-net
  zeppelin:
    container_name: zeppelin
    image: zeppelin_image_epetxepe
    build: ./zeppelin
    ports:
      - 80:8080
    volumes:
      - ./notebook:/opt/zeppelin/notebook
      - ./logs:/opt/zeppelin/logs
      - ./run:/opt/zeppelin/run
    environment:
      CORE_CONF_fs_defaultFS: "hdfs://namenode:8020"
      SPARK_MASTER: "spark://spark-master:7077"
      MASTER: "spark://spark-master:7077"
      #SPARK_SUBMIT_OPTIONS: "--jars /opt/sansa-examples/jars/sansa-examples-spark-2016-12.jar"
    depends_on:
      - spark-master
      - namenode
    networks:
      - spark-net

networks:
  spark-net:
    external:
      name: spark-net
